version: '3.8'
services:
  backend:
    image: wissemmtiri/pfa-app-backend:latest
    container_name: pfa-backend
    ports:
      - "3000:3000"
    networks:
      - backend
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=${POSTGRES_USER}
      - DATABASE_PASSWORD=${POSTGRES_PASSWORD}
      - DATABASE_NAME=pfa
    # CONSIDER USING ENVIRONEMENT FILES
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 1m
      timeout: 10s
      retries: 3

  frontend:
    image: wissemmtiri/pfa-app-frontend:latest
    container_name: pfa-frontend
    ports:
      - "4200:4200"
    networks:
      - frontend
    depends_on:
      - backend
    environment:
      - API_URL=http://backend:3000
    # CONSIDER USING ENVIRONEMENT FILES
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4200"]
      interval: 1m
      timeout: 10s
      retries: 3

  db:
    image: postgres:16-alpine
    container_name: pfa-db
    ports:
      - "5432:5432"
    networks:
      - backend
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=pfa
    # CONSIDER USING ENVIRONEMENT FILES
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 1m
      timeout: 10s
      retries: 3
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:

networks:
  backend:
  frontend: